### ISSUE TITLE
change theme 

### ISSUE THREAD

**Issue by badbye** [damianavila/live_reveal#42]
Hi, damianavila, thanks for your amazing tool.

I want to change default theme of transformation to "linear". I edit the custom.js file, and try to reinstall this library, but returns:

**custom.js entry already exists.**

what should I do? I also try to delete the files "../nbextension/liveshow"

By the way, I change the theme by this way is not elegant. What about adding some choice box in the cell toolbar?

**Comment by damianavila** [comment]
OH... sorry for never answering to your question... somewhat I missed this thread.

>Right? 

Yes, you could use `python setup.py install --develop` to link the `live reveal master` with the default profile for quick development...

Closing here because it seems you solve the issue... reopen it if it is not the case.
